name: unraid-smart-cache-exporter

services:
  unraid-smart-cache-exporter:
    image: ghcr.io/jski/unraid-smart-cache-exporter:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unraid-smart-cache-exporter
    restart: unless-stopped
    ports:
      - "9903:9903"
    environment:
      - LISTEN_PORT=9903
      - SMART_DIR=/var/local/emhttp/smart
      - DISKS_INI=/var/local/emhttp/disks.ini
      - EXCLUDE_NON_PRESENT=true
    volumes:
      - /var/local/emhttp/smart:/var/local/emhttp/smart:ro
      - /var/local/emhttp/disks.ini:/var/local/emhttp/disks.ini:ro
